export const Specialty = [
  'Acupuntura',
  'Alergia e Imunologia',
  'Anestesiologia',
  'Angiologia',
  'Angiorradiologia',
  'Cancerologia',
  'Cardiologia',
  'Cardiologia Pediátrica',
  'Cirurgia Cardiovascular',
  'Cirurgia Endovascular',
  'Cirurgia Geral',
  'Cirurgia Pediátrica',
  'Cirurgia Plástica',
  'Cirurgia Torácica',
  'Cirurgia Vascular',
  'Cirurgia da Mão',
  'Cirurgia do Trauma',
  'Citopatologia',
  'Clínica Médica',
  'Coloproctologia',
  'Densitometria Óssea',
  'Dermatologia',
  'Ecocardiografia',
  'Endoscopia',
  'Endoscopia Digestiva',
  'Endoscopia Ginecológica',
  'Endoscopia Respiratória',
  'Ergometria',
  'Foniatria',
  'Gastroenterologia',
  'Genética Médica',
  'Geriatria',
  'Ginecologia',
  'Hansenologia',
  'Hematologia',
  'Hematologia',
  'Hemodinâmica',
  'Hemoterapia',
  'Hemoterapia Pediátrica',
  'Hepatologia',
  'Homeopatia',
  'Imunologia Pediátrica',
  'Infectologia',
  'Infectologia Hospitalar',
  'Infectologia Pediátrica',
  'Mamografia',
  'Mastologia',
  'Medicina Fetal',
  'Medicina Paliativa',
  'Medicina Tropical',
  'Medicina de Urgência',
  'Medicina do Adolescente',
  'Medicina do Sono',
  'Nefrologia',
  'Nefrologia Pediátrica',
  'Neonatologia',
  'Neurocirurgia',
  'Neurofisiologia Clínica',
  'Neurologia',
  'Neurologia Pediátrica',
  'Neurorradiologia',
  'Nutrologia',
  'Nutrologia Pediátrica',
  'Obstetrícia',
  'Oftalmologia',
  'Ortopedia e Traumatologia',
  'Otorrinolaringologia',
  'Patologia',
  'Patologia Clínica',
  'Pediatria',
  'Pneumologia',
  'Pneumologia Pediátrica',
  'Psicogeriatria',
  'Psicoterapia',
  'Psiquiatria',
  'Psiquiatria Forense',
  'Radiologia',
  'Radioterapia',
  'Reumatologia',
  'Reumatologia Pediátrica',
  'Sexologia',
  'Ultrassonografia',
  'Urologia',
];

export const Value = [100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 750, 800, 850, 900,950, 1000, 1050];